name: deploy-release
on:
  push:
    tags:
      - 'v\d+(\.\d+){2}'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    env:
      RESUME_NAME: robertus-diawan-chris-resume

    steps:
      - name: Checkout current ref
        uses: actions/checkout@v4

      - name: Build resume
        run: make name="$RESUME_NAME"

      - name: Upload to github release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./${{ env.RESUME_NAME }}.pdf
          asset_name: ${{ env.RESUME_NAME }}.pdf
